name: linear-elastic-plate-with-hole
dependencies:
  - python>=3.11
  - pip:
      - "git+https://github.com/izus-fokus/snakemake-report-plugin-metadata4ing@v2.0.2#egg=snakemake-report-plugin-metadata4ing"
