site_name: Linear Elastic Plate with Hole Benchmark

repo_url: https://github.com/Simulation-Benchmarks/linear-elastic-plate-with-hole
edit_uri: blob/main/docs/

theme:
  name: readthedocs
  highlightjs: true
  icon:
    repo: fontawesome/brands/github

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - search
  - bibtex:
      bib_file: "docs/literature.bib"
  - include_dir_to_nav:
      recurse: false
      file_pattern: '.*\.(md|ipynb)$'
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      execute: false
      include_source: True

markdown_extensions:
  - admonition
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - pymdownx.tasklist:
  - pymdownx.superfences

nav:
  - Getting Started:
    - getting_started/workflow.md
    - getting_started/rohub.md
  - Benchmark:
    - "benchmark/plate-with-hole.md"
  - "zz_bibliography.md"

