name: fenics-model-validation
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - pip:
      - "git+https://github.com/Simulation-Benchmarks/semantic-benchmark.git@29-reporter-plugin-from-snakemake-repository"
      - "git+https://github.com/snakemake/snakemake-report-plugin-rocrate"
