name: fenics-model-validation
channels:
  - conda-forge
dependencies:
  - snakemake
  - pip
  - pip:
      - "git+https://github.com/izus-fokus/snakemake-report-plugin-metadata4ing@v1.2.6#egg=snakemake-report-plugin-metadata4ing"