name: edelweissfe_postprocessing
# Environment file for create_metrics.py. Called by the EdelweissFE tool workflow.

channels:
  - conda-forge

channel_priority: strict

dependencies:
  - python=3.12
  - numpy
  - pint
  - pyvista
  - sympy
