name: extendablefem-model-validation
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - pip:
      - "semantic-benchmark @ git+https://github.com/Simulation-Benchmarks/semantic-benchmark.git@22-adding-tool-name-and-software-version-to-final-rocrate"
      - "git+https://github.com/izus-fokus/snakemake-report-plugin-metadata4ing@v2.0.4#egg=snakemake-report-plugin-metadata4ing"
