name: RoHub Upload CI

on:
  schedule:
    - cron: '0 17 * * 5'
    
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to run and publish
        required: true
        default: main
      use_production_rohub:
        description: Upload to production RoHub
        required: true
        type: boolean
        default: true
      fenics_software_version:
        description: FEniCS version used for this run
        required: true
        type: string
        default: '0.9.0'
      kratos_software_version:
        description: Kratos version used for this run
        required: true
        type: string
        default: '10.3.0'
      extendablefem_software_version:
        description: ExtendableFEM version used for this run
        required: true
        type: string
        default: '1.12.0'
      edelweissfe_software_version:
        description: EdelweissFE version used for this run
        required: true
        type: string
        default: '26.03'

permissions:
  contents: read

jobs:
  run-fenics:
    uses: ./.github/workflows/run-benchmark-fenics.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      software_version: ${{ inputs.fenics_software_version || '0.9.0' }}

  run-kratos:
    uses: ./.github/workflows/run-benchmark-kratos.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      software_version: ${{ inputs.kratos_software_version || '10.3.0' }}

  run-extendablefem:
    uses: ./.github/workflows/run-benchmark-extendablefem.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      software_version: ${{ inputs.extendablefem_software_version || '1.12.0' }}

  run-edelweissFE:
    uses: ./.github/workflows/run-benchmark-edelweissfe.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      software_version: ${{ inputs.edelweissfe_software_version || '26.03' }}

  upload:
    needs: [run-fenics, run-kratos, run-extendablefem, run-edelweissFE]
    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: fenics
            display_name: Fenics
            software_url: https://zbmath.org/software/4314
            software_version: ${{ inputs.fenics_software_version || '0.9.0' }}
          - tool: kratos
            display_name: Kratos
            software_url: https://zbmath.org/software/7804
            software_version: ${{ inputs.kratos_software_version || '10.3.0' }}
          - tool: extendablefem
            display_name: ExtendableFEM
            software_url: https://zbmath.org/software/53664
            software_version: ${{ inputs.extendablefem_software_version || '1.12.0' }}
          - tool: edelweissFE
            display_name: EdelweissFE
            software_url: https://zenodo.org/records/20496210
            software_version: ${{ inputs.edelweissfe_software_version || '26.03' }}
    uses: ./.github/workflows/upload-rocrate.yml
    with:
      tool: ${{ matrix.tool }}
      display_name: ${{ matrix.display_name }}
      software_url: ${{ matrix.software_url }}
      software_version: ${{ matrix.software_version }}
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      use_production_rohub: ${{ inputs.use_production_rohub }}
    secrets: inherit
