name: RoHub Upload CI

on:
  schedule:
    - cron: '0 17 * * 5'
    
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to run and publish
        required: true
        default: main
      use_production_rohub:
        description: Upload to production RoHub
        required: true
        type: boolean
        default: true
      fenics_tool_version:
        description: FEniCS version used for this run
        required: false
        type: string
      kratos_tool_version:
        description: Kratos version used for this run
        required: false
        type: string
      extendablefem_tool_version:
        description: ExtendableFEM version used for this run
        required: false
        type: string
      edelweissfe_tool_version:
        description: EdelweissFE version used for this run
        required: false
        type: string

permissions:
  contents: read

jobs:
  run-fenics:
    uses: ./.github/workflows/run-benchmark-fenics.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      tool_version: ${{ inputs.fenics_tool_version || '0.9.0' }}

  run-kratos:
    uses: ./.github/workflows/run-benchmark-kratos.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      tool_version: ${{ inputs.kratos_tool_version || '10.3.0' }}

  run-extendablefem:
    uses: ./.github/workflows/run-benchmark-extendablefem.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      tool_version: ${{ inputs.extendablefem_tool_version || '1.12.0' }}

  run-edelweissFE:
    uses: ./.github/workflows/run-benchmark-edelweissfe.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      tool_version: ${{ inputs.edelweissfe_tool_version || '26.03' }}

  upload-fenics:
    needs: run-fenics
    uses: ./.github/workflows/upload-rocrate.yml
    with:
      tool: fenics
      display_name: Fenics
      used_software_url: https://zbmath.org/software/4314
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      use_production_rohub: ${{ github.event_name != 'workflow_dispatch' || inputs.use_production_rohub }}
    secrets: inherit

  upload-kratos:
    needs: run-kratos
    uses: ./.github/workflows/upload-rocrate.yml
    with:
      tool: kratos
      display_name: Kratos
      used_software_url: https://zbmath.org/software/7804
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      use_production_rohub: ${{ github.event_name != 'workflow_dispatch' || inputs.use_production_rohub }}
    secrets: inherit

  upload-extendablefem:
    needs: run-extendablefem
    uses: ./.github/workflows/upload-rocrate.yml
    with:
      tool: extendablefem
      display_name: ExtendableFEM
      used_software_url: https://zbmath.org/software/53664
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      use_production_rohub: ${{ github.event_name != 'workflow_dispatch' || inputs.use_production_rohub }}
    secrets: inherit

  upload-edelweissFE:
    needs: run-edelweissFE
    uses: ./.github/workflows/upload-rocrate.yml
    with:
      tool: edelweissFE
      display_name: EdelweissFE
      used_software_url: https://zenodo.org/records/20496210
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      use_production_rohub: ${{ github.event_name != 'workflow_dispatch' || inputs.use_production_rohub }}
    secrets: inherit
