name: Fenics and Kratos CI
on:
  push:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow once per day at 3:15am
  schedule:
    - cron: '3 16 * * *'

env:
  CACHE_NUMBER: 1  # increase to reset cache manually

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
            miniforge-version: latest
            use-mamba: true
        
      - name: Create fenics environment
        run: mamba env create -n fenics-model-validation -f fenics/environment_benchmark.yml

      - name: Run linear-elastic-plate-with-hole using fenics
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/fenics/
          conda run -n fenics-model-validation python run_benchmark.py

      - name: Create kratos environment
        run: mamba env create -n kratos-model-validation -f kratos/environment_benchmark.yml

      - name: Run linear-elastic-plate-with-hole using kratos
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/kratos/
          conda run -n kratos-model-validation python run_benchmark.py

      - name: Archive results of the fenics run of linear-elastic-plate-with-hole
        uses: actions/upload-artifact@v4
        with:
            name: fenics_results_linear-elastic-plate-with-hole
            path: |
              fenics/results/

      - name: Archive results of the kratos run of linear-elastic-plate-with-hole
        uses: actions/upload-artifact@v4
        with:
            name: kratos_results_linear-elastic-plate-with-hole
            path: |
              kratos/results/